logging:
  level:
    ru.yandex.practicum.telemetry: trace
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.jdbc.datasource.init: DEBUG

spring:
  sql:
    init:
      mode: always
      schema: classpath:/schema.sql
      data: classpath:/data.sql
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_home_db?currentSchema=shopping_store
    username: telemetry_user
    password: secret
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 1
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true